import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  DynamicContextProvider,
  DynamicWidget,
} from "@dynamic-labs/sdk-react-core";

import { EthereumWalletConnectors } from "@dynamic-labs/ethereum";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DynamicContextProvider
        settings={{
          environmentId: "a47f08df-6fd5-4b89-8036-39129e9debbf",
          walletConnectors: [EthereumWalletConnectors],
        }}
      >
        <body className={inter.className}>
          <DynamicWidget />
          {children}
        </body>
      </DynamicContextProvider>
    </html>
  );
}
